### ISSUE TITLE
Make it easier to create views.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#10]
Views can be created by using the `PutDocumentOperation` to create a ddoc, this may not be intuitive to new users of Cloudant/CouchDb so we should provide some helpers to make this eaiser. This could be achieved by extending the regular document operation and add properties for views etc.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
