### ISSUE TITLE
Make it possible to create a sort struct with a string literal.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#111]
Currently to create an array for the `fields` option on `CreateJSONQueryIndexOperation` you have the do the following:

``` swift
[Sort(field:"foo", sort: nil)]
```

this is painful for someone who wants the default sort. To combat this we could make it possible to create a sort struct from a string literal, where the string would be the field name, this would create the struct with `nil` sort direction.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
