### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#121]
With the merging of `URLSession` into swift corelibs, (See https://github.com/apple/swift-corelibs-foundation/pull/426) it should be possible to compile on Linux. 

Once a snapshot is published we should take the opportunity to see if we compile on linux and fix and issues that arise.

**Comment by rolivieri** [comment]
@rhyshort Hello, it is our understanding that with the latest development snapshot (8/25), libdispatch, NSURLSession and friends are now available: https://swift.org/download/#snapshots.

**Comment by rhyshort** [comment]
Yes they are available, there a few niggles to get through, so far I've got library compiling on Linux, just need to fix up the tests.

**Comment by rolivieri** [comment]
That's great! Looking forward to using the Cloudant SDK on linux.

**Comment by rhyshort** [comment]
Being able to test on Linux is currently blocked by [SR-2170](https://bugs.swift.org/browse/SR-2170).

**Comment by rhyshort** [comment]
Bad news on this. With the release of Swift 3, there are still issues that we can't overcome. The biggest being unable to link due to [SR-2170](https://bugs.swift.org/browse/SR-2170). Which has yet to be fixed (error attached below). I think we will need to wait for a few patch releases before we can add linux support as it currently stands.

Error:

```
Linking ./.build/debug/SwiftCloudantPackageTests.xctest
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationg6_queueXwGSqCS_14OperationQueue_' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operations6_queueXwGSqCS_14OperationQueue_' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationm6_queueXwGSqCS_14OperationQueue_' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationg10_cancelledSb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operations10_cancelledSb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationm10_cancelledSb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationg10_executingSb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operations10_executingSb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationm10_executingSb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationg9_finishedSb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operations9_finishedSb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationm9_finishedSb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationg6_readySb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operations6_readySb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationm6_readySb' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationg13_dependenciesGVs3SetS0__' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operations13_dependenciesGVs3SetS0__' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationm13_dependenciesGVs3SetS0__' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationg6_groupC8Dispatch13DispatchGroup' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operations6_groupC8Dispatch13DispatchGroup' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationm6_groupC8Dispatch13DispatchGroup' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationg9_depGroupC8Dispatch13DispatchGroup' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operations9_depGroupC8Dispatch13DispatchGroup' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationm9_depGroupC8Dispatch13DispatchGroup' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationg7_groupsGSaC8Dispatch13DispatchGroup_' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operations7_groupsGSaC8Dispatch13DispatchGroup_' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operationm7_groupsGSaC8Dispatch13DispatchGroup_' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operation12_leaveGroupsfT_T_' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operation6finishfT_T_' is not defined locally
/usr/bin/ld.gold: error: hidden symbol '_TFC10Foundation9Operation15_waitUntilReadyfT_T_' is not defined locally
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by rhyshort** [comment]
The related [SR-1901](https://bugs.swift.org/browse/SR-1901) has been fixed. Not sure if it would fix the issue throughout foundation without verification however. 

There are also a couple of issues with `Foundation` on linux JSONSeralisation, booleans are stored as `NSNumber` on linux and can't be cast to `Bool` like it can be on Apple platforms. HTTPCookieStorage is also lacking the `shared` storage option, we use it so we can access cookies later, and have our tests interact with the same cookie storage object.

**Comment by rhyshort** [comment]
Small update, all of HTTPCookieStorage is currently unimplemented see https://github.com/apple/swift-corelibs-foundation/blob/7400a09/Foundation/NSHTTPCookieStorage.swift

**Comment by pushkarnk** [comment]
Yes, we'll start looking at HTTPCookieStorage.

**Comment by rhyshort** [comment]
HTTPCookieStorage PR https://github.com/apple/swift-corelibs-foundation/pull/672 its been open quite a while and doesn't look like its going to get merged anytime soon.

**Comment by rhyshort** [comment]
With https://github.com/apple/swift-corelibs-foundation/pull/836 merged, one less barrier to running on linux.

**Comment by rolivieri** [comment]
@rhyshort Swift 3.1 is out now; hopefully the change above is included in these latest binaries.

**Comment by benspratling4** [comment]
Is this fixed in Swift 3.1?

**Comment by rhyshort** [comment]
No not yet, cookie support hasn't been merged so that is still a blocker.

**Comment by rhyshort** [comment]
The linux testing will need to be expanded from just 14.04, to cover:

- 14.04
- 16.04
- 16.10

should be straight forward to add to the matrix.

**Comment by ianpartridge** [comment]
I've just merged the `linux-support` branch to `master`. With this, the Cloudant testsuite passes on Linux when run against the latest Swift 4 snapshot from `swift.org`.

**Comment by ricellis** [comment]
Thanks @ianpartridge 
We'll have to figure out whether this library becomes Swift 4 only or how easy it is to support both 4 and 3 (for non-linux).

**Comment by ianpartridge** [comment]
As of today it compiles on both Swift 3 and 4, so hopefully we can support both.

**Comment by gmosx** [comment]
Now that Swift 4 is released, what's the status of this issue?

**Comment by rhyshort** [comment]
There are currently test failures that need investigating: https://travis-ci.org/cloudant/swift-cloudant/jobs/277632910

**Comment by ianpartridge** [comment]
Hmm, that's annoying, it must be a regression somewhere.

**Comment by gmosx** [comment]
So, any updates?

**Comment by ricellis** [comment]
I'm closing this ticket, the Linux support work in this library has been done for quite a while (although not released). There is a remaining issue with the `GetChangesOperation` which I think should be tracked separately.
