### ISSUE TITLE
Tag version of 25/7

### ISSUE THREAD

**Issue by GilGS** [cloudant/swift-cloudant#123]
Hi.
I need to use your 25/7 version - 
https://github.com/cloudant/swift-cloudant/commit/5093b96367c63152073e30229ba84eeb5cb26494

Can you please tag this commit so I can pull it?
Thanks.

**Comment by rhyshort** [comment]
Sure, it's available here: https://github.com/cloudant/swift-cloudant/releases/tag/0.5.0

Note: I didn't perform the updates for CocoaPods, we intend to do that as part of our next planned release.

**Comment by GilGS** [comment]
Thanks!
