### ISSUE TITLE
Simplify Cookie Handling.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#124]
URLSession should handle all the functions around Cookie authentication apart from requesting the cookie. To this end, the interceptor functionality should be folded into `InterceptableSession`, and it should only make a session request when:

1. It is the first request for the session.
2. A task returned a Forbidden Error Code, with the credentials expired message.

However it should be noted that if getting a cookie fails for any reason other than a 401, it should
be retired for an amount of retires, configurable from the client.

In an long running application making enough requests, it should only be in rare situations where case 2) is invoked.

**Comment by ricellis** [comment]
Since different CouchDB versions and Cloudant versions do different things I think case 2 needs to handle a 401, as well as the 403 credentials_expired.
