### ISSUE TITLE
Update installation procedure

### ISSUE THREAD

**Issue by peterschleinitz** [cloudant/swift-cloudant#125]
did no run on Mac OS 10.11.6

    pod SwiftCloudant, :git => 'https://github.com/cloudant/swift-cloudant.git'

output:

    [!] Invalid `Podfile` file: uninitialized constant Pod::Podfile::SwiftCloudant.
----
this statement ran: 

    pod 'SwiftCloudant', :git => 'https://github.com/cloudant/swift-cloudant.git'

output:

    Installing SwiftCloudant (0.4.0)
    Pod installation complete! There are 2 dependencies from the Podfile and 3 total
    pods installed.

**Comment by rhyshort** [comment]
Ah typo, thanks for catching that
