### ISSUE TITLE
Make it possible to add additional parameters to an Operation

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#131]
Currently in swift cloudant all operations can not be subclassed from outside of the SwiftCloudant module. This causes problems if a new parameter is added to the endpoint but we do not yet directly support through the library. In order for the user to use this new parameter they will need to create their own Operation, which is alot of work for just a single parameter. We should either make all operations `open` so users can add their own properties to operation for parameters or provide an API to add arbitrary parameters to a request.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
