### ISSUE TITLE
Improve Logging

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#132]
Please include the following information in your ticket.
- SwiftCloudant version(s) that are affected by this issue. All
- Swift version(s) 3.0
- Platform(s) All.
- A small code sample that demonstrates the issue. n/a

Currently the library only logs for `_session` request/response processing. This needs to be enhanced  to cover enough of the library that when someone reports an issue it is possible to identity the problem. If we use a third party logging framework, it will need to support distribution through CocoaPods and SwiftPM.

There are a few built in solutions, there is `NSLog` although that may not be that helpful. There is a new logging framework for macOS 10.12, iOS 10, tvOS 10, watchOS 3, which is unified logging, as part of the `os` framework.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
