### ISSUE TITLE
CouchDBClient should remove URL creds or error.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#141]
CouchDBClient allows for credentials to be passed via the URL and via the `username` and `password` parameters, we should either throw an error if they are present or remove them from the `url`.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
