### ISSUE TITLE
HTTPInterceptorContext needs to be removed.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#145]
HTTPInterceptorContext needs to be removed, it was part of the interceptor API that was removed in favour of a different implementation for supporting functionality such as 429 back off and cookie authentication.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
