### ISSUE TITLE
Remove Workaround for test Settings

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#146]
Remove the workaround for  TestHelpers.TestSettings when SPM allows bundling of test resources.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
