### ISSUE TITLE
CONTRIBUTING.md needs updating

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#148]
Contributing document needs to be updated to reflect that SwiftCloudant should be developed on the latest stable release of Swift, rather than the latest development snapshot.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
