### ISSUE TITLE
Swift 3.1 Warning

### ISSUE THREAD

**Issue by no404here** [cloudant/swift-cloudant#151]
I'm getting this warning with Swfit 3.1:

> Property should not be declared fileprivate because its type uses a private type

Is there any way to fix this or can you update the framework to be compatible with the new version of swift please?

**Comment by rhyshort** [comment]
Sorry for the delay, didn't notice this in my notifications. There isn't a way to fix it although I think the warning disappears in Swift 3.0. I've opened a PR to fix it, although I can't any timelines on when a release containing the fix will be released.
