### ISSUE TITLE
Performance Improvement needs : when getting batch data from cloudant db 

### ISSUE THREAD

**Issue by yinglidl** [cloudant/swift-cloudant#157]
Please include the following information in your ticket.

- SwiftCloudant version(s) that are affected by this issue.
when getting data from cloudant DB using 'GetDocumentOperation', it needs about 2,3seconds to get one document. When want to show the data from cloudant DB in a XCODE storyboard table view list, it may need to get 20 - 30 data once time , it needs about 2 minutes to complete this action.
- Swift version(s)
0.6.0
- Platform(s)
macOS
- A small code sample that demonstrates the issue.

**Comment by ricellis** [comment]
You could try using the `GetAllDocsOperation` with `keys` of the doc IDs that you want and `includeDocs`. That will make just one request instead of one per doc ID.

**Comment by yinglidl** [comment]
Thank you for your advice, we have tried GetAllDocsOperation ,still it needs almost the same time to response...

**Comment by ricellis** [comment]
Does it take nearly the same time to get the same documents using another tool, for example like `curl`? 
I don't think swift-cloudant does anything that should particularly slow things down, it could just be limited by the document size and the network connection or if you are being rate limited on your Cloudant account.

**Comment by yinglidl** [comment]
I have tried according to your comment, and it works now very well. Thank  you so much !
