### ISSUE TITLE
Please Make it possible to Update a Document, the parameter is the key of the dictionary

### ISSUE THREAD

**Issue by yinglidl** [cloudant/swift-cloudant#163]
Please include the following information in your ticket.

- SwiftCloudant version(s) that are affected by this issue.
- Swift version(3.0)
- Platform(macOS)

We are using this resource to access Cloudant DB smoothly, I am very appreciate your contribution about this resource. But since there is such a method which can update a Doc by specify the KEY value.  Is there any method I can use to UPDATE DOC, or would you please make it possible ?

Thanks very much !

**Comment by ricellis** [comment]
The [PutDocumentOperation](https://github.com/cloudant/swift-cloudant/blob/master/Source/SwiftCloudant/Operations/Documents/PutDocumentOperation.swift#L25) with a specified `revision` is used to update documents. Just set the `revision` to the revision that should be updated and the `body` to the new content.

**Comment by ricellis** [comment]
Currently Couch does not support, for example, the HTTP `PATCH` method so there is no way to update a single document key.

**Comment by yinglidl** [comment]
Thank you for your answer, I will try, and will feedback the result. Thanks again and have a nice day !
