### ISSUE TITLE
Can not obtain document's values and use in other function by GetDocumentOperation

### ISSUE THREAD

**Issue by yanglisc** [cloudant/swift-cloudant#164]
Please include the following information in your ticket.

- SwiftCloudant version(s) that are affected by this issue:latest version
- Swift version(s):swift3.1
- Platform(s):macOS 10.12.2, xcode8.3.3
- A small code sample that demonstrates the issue:
I want to list document with some of it's items in the tableview.
I used the GetDocumentOperation and get the items by "response"(response1).But I can not obtain these values in other function,even though use global variable.
It seems GetDocumentOperation is last executed, and it will do nothing after executing GetDocumentOperation .
Is there any solution to solve my requirement。
-----------------------------------
```swift
var dicArray:Array<Dictionary<String, Any>> = []  //global variable,used to save the items of the document
...
func dealWithdic(){
        dbcnntModel1.getDocuments(userID:userName)  //call GetDocumentOperation
        print(dicArray)    //nothing,it seems not execute this statement。
}
...
func getDocuments(userID:String) {
        let client1 = CouchDBClient(url:cloudantURL as URL, username: accountNo, password: pwd)
        let read1 = GetDocumentOperation(id: userID, databaseName: dbName){(response1, HTTPInfo,error) in
            if let error1 = error {
                //print("Encountered an error while reading a document. ERROR:\(error1)")
            }
            else {
                dicArray= response1?["doc"] as! Array<Dictionary<String, Any>> //get the items's value and let dicArray = these values
            }
        }
        client1.add(operation:read1)
    }

```

**Comment by rhyshort** [comment]
I have a small question about your code sample, does the document you are retrieving from the database have the property `doc`?

**Comment by ricellis** [comment]
@yanglisc the `response1` parameter in the completion handler callback closure is a `Dictionary` of the JSON document body retrieved by the operation. So as @rhyshort says the document needs to have the `doc` property for your example code to be able to assign it.

Does your document contain a `doc` property that is an array of nested JSON objects?

**Comment by ricellis** [comment]
Closing as stale, please re-open if further help is required.
