### ISSUE TITLE
Support for Codable with Swift 4?

### ISSUE THREAD

**Issue by jthomas** [cloudant/swift-cloudant#169]
Are there plans to update the API to support types with Codable support?
https://grokswift.com/json-swift-4/

This would allow developers to pass native types to the create APIs rather than a raw dictonary. It could also be used with generics to automatically deserialise JSON to types from the read APIs.

**Comment by tomblench** [comment]
Thanks for bringing this to our attention, this looks like the right way to do (de)serialisation.

We'll prioritise onto our backlog but beware that work for our other client libraries may take priority.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
