### ISSUE TITLE
Kitura bluemix

### ISSUE THREAD

**Issue by thedarkdima** [cloudant/swift-cloudant#172]
Can't work with swift-cloudnat on Kitura bluemix no clue if the problem with swift-cloudnat or on their end.

**Comment by emlaver** [comment]
Hi @thedarkdima, could you please explain in more detail what issue(s) you are witnessing? 

If you are new to Swift and Bluemix, I would recommend completing the steps in this tutorial: https://console.bluemix.net/docs/runtimes/swift/getting-started.html#getting-started-tutorial.

**Comment by thedarkdima** [comment]
Hi @emlaver, I am using the last version of swift-cloudant as I understood it written in swift 3 and for some magical reason kitura server on blumix can run only swift 4, even though on XCode kitura runs it without a problem. Anyway, I just pulled swift-cloudant for swift 4 from one of the branches and that fixed the problem so I am just working with it. Thanks for the reply.
