### ISSUE TITLE
Operation.Error visibility

### ISSUE THREAD

**Issue by nikwest** [cloudant/swift-cloudant#181]
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

## Bug Description

Operation.Error enum types are not visible outside package. This way I cannot catch specific errors, but only generic errors which gives a generic message: "The operation couldn’t be completed. (SwiftCloudant.Operation.Error error 1.)"

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

From the example:
// Create a document
let create = PutDocumentOperation(id: "doc1", body: ["hello":"world"], databaseName: dbName) {(response, httpInfo, error) in
    if let error = error {
        print("Encountered an error while creating a document. Error:\(error)")
    } else {
        print("Created document \(response?["id"]) with revision id \(response?["rev"])")
    }
}
client.add(operation:create)

### 2. What you expected to happen

// Create a document
let create = PutDocumentOperation(id: "doc1", body: ["hello":"world"], databaseName: dbName) {(response, httpInfo, error) in
    if let error = error {
        switch error {
       case let opError as Operation.Error.http:
           print("http error occurred: \(opError.statusCode):   \(opError.response)
       default:
           print("Encountered an error while creating a document. Error:\(error)")
       }
    } else {
        print("Created document \(response?["id"]) with revision id \(response?["rev"])")
    }
}
client.add(operation:create)

### 3. What actually happened
   Code from 2 does not compile due to visibility of Operation.Error:
"'Error' is inaccessible due to 'internal' protection level"

## Environment details
OSX Mojave, Swift 4.2

**Comment by tomblench** [comment]
@nikwest you're right this should probably be visible outside the package.

If this is something you urgently require, you can submit a PR for this (following the template and signing the CLA). Otherwise we'll prioritise it onto our backlog.
