### ISSUE TITLE
InterceptableSession is not thread safe, but will be called from different threads

### ISSUE THREAD

**Issue by nikwest** [cloudant/swift-cloudant#190]
## Bug Description
my app crashes frequently when under load:

debugger reports this line:

        self.taskDict[nsTask] = task

in InterceptableSession:dataTask(request: URLRequest, delegate: InterceptableSessionDelegate)

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

Create a bunch (>25 in my case) of Operations and add them to the CouchDB client 

### 2. What you expected to happen

Expectation is that the operations should execute in a sequential order (usually max 2-3 concurrent requests per client is standard)

### 3. What actually happened

There seems to be a problem that the taskDict is accessed from different threads which the OperationQueue is using and tasks are added and removed to that dictionary concurrently without protection.

## Environment details
Swift 5.0 on Mac OS X

**Comment by nikwest** [comment]
Setting the max concurrent count to 1 for the operation queue in CouchDBClient solves the problem.
This should be a configurable option anyways as #76 suggests. I don't think it is safe right now to have it anything else than 1 though.

        queue.maxConcurrentOperationCount = 1

**Comment by emlaver** [comment]
@nikwest Thanks for investigating! We'll prioritize this onto our backlog.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
