### ISSUE TITLE
http request timeout is hard coded to 10s

### ISSUE THREAD

**Issue by nikwest** [cloudant/swift-cloudant#191]
## Bug Description

http request timeout is hard coded to 10s. In our case when uploading larger data chunks with restricted network throughput  the request will time out.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
Create a put request which uploads data which will take longer than 10s to upload.

### 2. What you expected to happen
Upload to finish successfully. Default timeout of a NSURLRequest is 60s.

### 3. What actually happened
Time out error occurs, because the default is overwritten within swift-cloudant to 10s. There is no way to configure this. At least this option should be configureable globally or per operation.

**Comment by emlaver** [comment]
Hi @nikwest thanks for reporting this! I want to confirm that this is the code you are referring to: https://github.com/cloudant/swift-cloudant/blob/e363c22e716e5967cb8c564b86c84fdee3360646/Source/SwiftCloudant/HTTP/RequestBuilder.swift#L125.
We'll prioritize this onto our backlog.

**Comment by nikwest** [comment]
Yes, exactly. Sorry, didn’t know how to do this fancy code references ;)

**Comment by bessbd** [comment]
@nikwest : are you interested in submitting a PR for this?

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
