### ISSUE TITLE
Support the _uuids endpoint

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#29]
Support the _uuids endpoint to return a list of uuids that can be used for document ids. See [CouchDb documentation](http://couchdb.readthedocs.org/en/1.6.1/api/server/common.html#uuids)

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
