### ISSUE TITLE
Support the _stats endpoint

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#30]
Support the _stats endpoint to allow users to get information on their CouchDB instance. See [CouchDB docs](http://couchdb.readthedocs.org/en/1.6.1/api/server/common.html#uuids)

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
