### ISSUE TITLE
Investigate support for Carthage 

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#6]
Investigate supporting Carthage as a package manager for swift-cloudant.

**Comment by nikwest** [comment]
I added 
```
github "cloudant/swift-cloudant"
```
to my Cartfile.

Then I did 

```
my-project> carthage checkout swift-cloudant 
```

then 
```
my-project> cd Carthage/Checkouts/swift-cloudant/
swift-cloudant> swift package generate-xcodeproj
generated: ./SwiftCloudant.xcodeproj
swift-cloudant> cd -
my-project> carthage build --platform ios swift-cloudant
```

This created a SwiftCloudant.framework in the Carthage/Builds/iOS directory, which I added to my project, like all other Carthage dependencies.
So it kind of worked, you only need to generate the Xcode project manually.

**Comment by rhyshort** [comment]
Great glad it sort of works, thanks for checking that out for us. We can solve the manual step of generating the Xcode project, with checking in a generated project.

**Comment by nikwest** [comment]
For iOS you have to provide a different info.plist with a correct product identifier. I can provide you a pull request once I'm back  end of January.

**Comment by rhyshort** [comment]
That would be great! Thank you  😄

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
