### ISSUE TITLE
Reduce duplication for operation validation

### ISSUE THREAD

**Issue by ricellis** [cloudant/swift-cloudant#68]
~Each Operation's `validate` method should start by calling `super.validate()` before performing it's own checks.~

**Comment by rhyshort** [comment]
Each operation has its own complete validation code to verify if the operation is valid, however some of these checks apply across operations, where possible we should reduce the duplication.

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
