### ISSUE TITLE
Make max number of operations configurable

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#76]
It should be possible to configure the maximum number of operations the queue which backs the client can run at a time, it should also be noted that it is reconmedned be set to `NSOperationQueueDefaultMaxConcurrentOperationCount` as per [apples doc](https://developer.apple.com/library/ios/documentation/Cocoa/Reference/NSOperationQueue_class/index.html)

**Comment by ricellis** [comment]
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/swift-cloudant/issues/?q=is%3Aissue+label%3AEOL) in case any forks want to import it.
