### ISSUE TITLE
Swift 3 Preview 1 Changes: NS Prefix removal.

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#82]
There are a bunch of changes to the Swift Runtime in the Swift Preview 1. 

A number of Swift Evolution proposals have landed for OS X. These include new Objc Bridgeable types. These types should replace their NS Prefixed version. [SE-0086](https://github.com/apple/swift-evolution/blob/master/proposals/0086-drop-foundation-ns.md)

Examples

`NSData` -> `Data`
`NSURLSession` -> `URLSession`
`NSJSONSeralisation` -> `JSONSeralisation`

In addition to this `NSMutableData` has been replace with `Data` as a value type see [SE-0069](https://github.com/apple/swift-evolution/blob/master/proposals/0069-swift-mutability-for-foundation.md).

**Comment by gmgershon** [comment]
Hi Rhys - Yes, I loaded the project into the latest XCode beta this week and the 3.0 migration tool offered to make these naming changes as well as many other code modifications.

**Comment by rhyshort** [comment]
Hmm interesting, I attempted to use the migrator earlier on master and it failed, assumed it was because it was expecting swift 2.2 rather than 3 code.

**Comment by gmgershon** [comment]
Suggest downloading the latest XCode beta and cloning into a fresh 3.0 workspace. It automatically prompted me to migrate to 3.0. There were between 50 and 100 messages from the migrator -- more than I cared to casually delve into, but they'd likely be easy for you.
