### ISSUE TITLE
Cannot use CouchDB to generate doc ids 

### ISSUE THREAD

**Issue by rhyshort** [cloudant/swift-cloudant#97]
Please include the following information in your ticket.
- SwiftCloudant version(s) that are affected by this issue: All released
- Swift version(s): N/A
- Platform(s): All
- A small code sample that demonstrates the issue.

``` swift
let put = PutDocumentOperation() 
put.body = ["hello":"world"] 
put.validate() // returns False instead of true,
```

Since Couch makes it possible to post a document without an id for one to be generated, we should be doing the same thing.

**Comment by rhyshort** [comment]
As part of the API review in #96 this could be fixed by keeping the docId optional, and performing a post instead, although this could also be achieved with a new operation which posts the doc to the database.

**Comment by theodoracheng** [comment]
@rhyshort is this going to be resolved anytime soon? I am also interested in using this feature

**Comment by rhyshort** [comment]
We don't have an ETA when we will get around to fixing it. There is a workaround however.

```swift
let createDocumentOperation(ID: UUID().uuidString, body: ["hello": "world"]) { response, httpInfo, error in 
    // do something
}
```
