### ISSUE TITLE
Sort struct in inaccessible for CreateJsonQueryIndexOperation

### ISSUE THREAD

**Issue by tfrank64** [cloudant/swift-cloudant#98]
Please include the following information in your ticket.

- SwiftCloudant version(s) that are affected by this issue. 0.3
- Swift version(s) Swift-Dev-Snapshot-06-06
- Platform(s) All
- A small code sample that demonstrates the issue.

Creating a Sort object does not work, giving the following error:

> Sort initializer is inaccessible due to internal protection level

```
let sort = Sort(field:"_id", sort: SortDirection.Desc)
```

I need this to work so I can assign it to the `fields` parameter of `CreateJsonQueryIndexOperation`
To replicate, try creating a Sort object in an app that uses Swift-Cloudant as a package.

**Comment by rhyshort** [comment]
The members of the struct should have been public, however we also need to provide the init method ourselves, if we don't the one generated will be a `internal` scope.

**Comment by rhyshort** [comment]
Released  @tfrank64's fix in 0.3, closing.
